export const Movies = [
    { id: 1, name: 'Ghost Doctor', rating: 7.9, img: 'https://www.viu.com/ott/id/articles/wp-content/uploads/2022/01/poster-spesial-ghost-doctor-viu-2.jpg', description: 'Bác sĩ ma (tiếng Hàn: 고스트 닥터; Romaja: Goseuteu Dagteo) là một bộ phim truyền hình của Hàn Quốc ra mắt năm 2022 được đạo diễn bởi Boo Seong-cheol và có sự tham gia diễn xuất của Rain, Uee, Kim Bum và Son Na-eun. Bộ phim xoay quanh hai bác sĩ có xuất thân và kỹ năng đối lập nhau nhưng lại bị hợp nhất vào một người.' },
    { id: 2, name: 'tale of the nine tailed', rating: 11.5, img: 'https://images.indianexpress.com/2022/05/tail1200.jpg', description: 'Bạn trai tôi là Hồ Ly (Hangul: 구미호뎐, Romaja quốc ngữ: Gumihodyeon) là bộ phim truyền hình Hàn Quốc ra mắt năm 2020, với sự tham gia của Lee Dong-wook, Jo Bo-ah và Kim Bum.[1][2] Bộ phim được khởi chiếu trên đài truyền hình tvN của Hàn Quốc vào mỗi thứ Tư và thứ Năm vào lúc 22:50 (KTS) hàng tuần từ ngày 7 tháng 10 đến ngày 3 tháng 12 năm 2020.' },
    { id: 3, name: 'Mouse', rating: 11.6, img: 'https://bloganchoi.com/wp-content/uploads/2021/03/mouse-kd-78.jpg', description: 'Mouse (tiếng Hàn: 마우스; Romaja: Mauseu) là loạt phim truyền hình mang đề tài hình sự, trinh thám giật gân của Hàn Quốc ra mắt năm 2021 với sự tham gia của Lee Seung-gi, Lee Hee-jun, Park Ju-hyun và Kyung Soo-jin.[1] Bộ phim do Choi Joon-bae đạo diễn và được chấp bút bởi biên kịch Choi Ran. Bộ phim được phát sóng trên đài tvN mỗi 22:30 KST thứ Tư và thứ Năm hàng tuần từ 3 tháng 3 đến 20 tháng 5 năm 2021.[2]' },
    { id: 4, name: 'Big Mouth', rating: 12, img: 'https://bloganchoi.com/wp-content/uploads/2022/08/poster-chinh-thuc.jpg', description: 'Bộ phim kể về kể về một luật sư tầm thường có tỉ lệ thắng án 10%, vô tình bị cuốn vào một cuộc điều tra án mạng khủng khiếp. Để bảo toàn tính mạng, bảo vệ gia đình và lột trần những âm mưu kinh hoàng của tầng lớp thế lực, anh bất đắc dĩ giả làm thiên tài lừa đảo khét tiếng "Big Mouse". [5]' },
    { id: 5, name: 'Extraordinary Attorney Woo', rating: 15.7, img: 'https://bazaarvietnam.vn/wp-content/uploads/2022/07/harper-bazaar-nu-luat-su-ky-la-woo-young-woo-extraordinary-attorney-woo-1.jpg', description: 'Nữ luật sư kỳ lạ Woo Young Woo kể câu chuyện về Woo Young-woo, một luật sư mắc chứng rối loạn phổ tự kỷ, làm việc tại một công ty luật lớn. Cô ấy có chỉ số IQ cao 164, trí nhớ siêu phàm và cách suy nghĩ sáng tạo, tuy nhiên chỉ số EQ thấp và kỹ năng xã hội của cô bị mai một.[5]' },
    { id: 6, name: 'Young Lady And Gentleman', rating: 38.2, img: 'https://static1.dienanh.net/dienanhnet/202110/2732fc1e-ebf5-4146-a532-0de121774bd5.jpeg', description: 'Dan Dan ( Lee Se-hee ) sống với cha, mẹ kế và anh kế của cô, Dae Bum, một doanh nhân luôn thất bại, người đã mất nhà và toàn bộ số tiền trong một vụ lừa đảo. Mệt mỏi vì phải chịu đựng chúng, cô bỏ nhà đi. Cảm thấy không may mắn, cô leo lên một ngọn núi như một cách tạm thời giải tỏa áp lực cuộc sống.' },
    { id: 7, name: 'Reply 1988', rating: 20.2, img: "https://occ-0-448-395.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABQiLySv67Z00six6BhU4PgKg_NXjsV_7gyzO_2FklWxZfb3-ZTCvYbGG8oH3WcDKvMdR3gibmujM2Kp7Wm25ubT4AdlKuHMCSyYj.jpg?r=751", description: 'Bắt đầu từ năm 1988, phim xoay quanh năm người bạn và gia đình của họ sống trong cùng khu phố Ssangmun-dong, quận Dobong, Bắc Seoul.' },
    { id: 8, name: 'our beloved summer', rating: 19, img: 'https://wallpapercave.com/wp/wp10513362.jpg', description: 'Một bộ phim hài lãng mạn dành cho tuổi thành niên xoay quanh Choi Woong (Choi Woo-shik) và Kook Yeon-soo (Kim Da-mi), hai người yêu cũ từng chia tay với lời hứa không bao giờ gặp lại. Thật may mắn khi bộ phim tài liệu mà họ quay cách đây 10 năm ở trường cấp ba bỗng nổi đình đám và buộc cả hai phải gặp lại nhau bởi người bạn chung thời cấp ba của họ là cũng là một đạo diễn phim tài liệu. Bộ phim mô tả những cảm xúc phức tạp và quá trình trưởng thành của họ.' }
]